### ISSUE TITLE
Hi  I want to use this library to test fps under difference user stories

### ISSUE THREAD

**Issue by oatsuper** [friendlyrobotnyc/TinyDancer#31]
I have a android phone without root permission, So i can't meet fps value shows

**Comment by digitalbuddha** [comment]
I'm not sure what you are asking?

**Comment by oatsuper** [comment]
Feeling embarrassed，I had import this library to my test demo, after install apk to my android phone. it  does not work ,i can not see the fps show on screen. This phone' android build type is release. 
But I installed my the same apk to another phone your library work well ,which phone with android eng version (ro.build.type]: [eng] from getprop command) 

I wanna know to get fps shows with a android phone without root permission

Thanks~~

**Comment by digitalbuddha** [comment]
You don't need root permission. What phone is it not working on? In app
info is there permission you can enable?

**Comment by oatsuper** [comment]
draw over other apps？？my app had get this permission  in settings info
which permission  in my app should request？

**Comment by oatsuper** [comment]
i don't know why it works after "pm clear <mypackagename>" haha

**Comment by digitalbuddha** [comment]
Weird. Glad it works now :-)

**Comment by oatsuper** [comment]
To Weird ～～ you can close this issue, sorry to trouble you ～
