### ISSUE TITLE
How can I find the reason of drop frames?

### ISSUE THREAD

**Issue by ihrthk** [friendlyrobotnyc/TinyDancer#32]
Is the have stack infomation can be supply?

**Comment by digitalbuddha** [comment]
I use DDMS.  Look into method tracing.  Basically you can say "start tracing" somewhere in your code do a bunch of actions and then have "stop tracing".  You can then generate a .trace file that either Android Studio or DDMS can view.  Using that trace file you can dive into what was slowing down your FPS performance.  When it comes to scrolling nothing can block main thread for more than 16ms

**Comment by ihrthk** [comment]
Thank you for ask my question.I get the 'TraceView' mode.But,When I should "start tracing" and '' stop tracing".Because I not sure When block main thread will be happend?How do you do?
