### ISSUE TITLE
Add "no-op" for "testCompile"

### ISSUE THREAD

**Issue by jaredsburrows** [friendlyrobotnyc/TinyDancer#34]
Similar to leak canary, can we add a "no-op"?

**Comment by digitalbuddha** [comment]
Sure!

**Comment by jaredsburrows** [comment]
I can help with this one as well. My idea is to keep it simple like https://github.com/square/leakcanary/tree/master/leakcanary-android-no-op.

**Comment by digitalbuddha** [comment]
Yup that works! Thanksl you kindly  for the help. (also I can just get it in over weekend)
