### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by jaredsburrows** [friendlyrobotnyc/TinyDancer#36]
Add TravisCI for continuous integration builds

**Comment by digitalbuddha** [comment]
Prs welcome ☺️ I'm actually not familiar with Travis but can take a look.
We do Jenkins internally

**Comment by jaredsburrows** [comment]
Sure. Let's start with this small one: https://github.com/friendlyrobotnyc/TinyDancer/pull/35

**Comment by jaredsburrows** [comment]
I can do this but I do not have access to your TravisCI. Make sure you add it https://travis-ci.org/!

**Comment by digitalbuddha** [comment]
Done

**Comment by jaredsburrows** [comment]
Awesome! Thanks!

**Comment by digitalbuddha** [comment]
I guess I'll start on writing tests https://github.com/friendlyrobotnyc/TinyDancer/issues/38

**Comment by jaredsburrows** [comment]
@digitalbuddha Sounds good. Some unit tests and android tests should do!
