### ISSUE TITLE
Automate deployment to maven

### ISSUE THREAD

**Issue by digitalbuddha** [friendlyrobotnyc/TinyDancer#42]
@jaredsburrows any best practices for maven/travis you can point me to?  Where to keep keys externalized etc.  

Thank you kindly

**Comment by jaredsburrows** [comment]
You can store keys in travis for auto deployment. Good for snapshots. I suggest doing the releases manually.

**Comment by jaredsburrows** [comment]
@digitalbuddha Did you get this working?
