### ISSUE TITLE
position does not change

### ISSUE THREAD

**Issue by jemshit** [friendlyrobotnyc/TinyDancer#48]
view position does not change even if i change it from Builder

**Comment by digitalbuddha** [comment]
The issue seems to be caused by both setting the gravity & x+y position. I'll have a fix in next version to ignore the gravity if there is a user configured starting x+y.  Thanks for reporting!

**Comment by brianPlummer** [comment]
@jemshit fixed in current master branch and will go with the 0.1.1 release tomorrow or the next
