### ISSUE TITLE
Remove permission "SYSTEM_ALERT_WINDOW" for no-op release

### ISSUE THREAD

**Issue by Gilianp** [friendlyrobotnyc/TinyDancer#50]
Hi, can you remove uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" for no-op release since it is not necessary for release, in AndroidManifest.xml

**Comment by Gilianp** [comment]
this permission
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

**Comment by digitalbuddha** [comment]
Sure! What to open pr?

**Comment by brianPlummer** [comment]
@Gilianp fixed in current master branch and will go with the 0.1.1 release tomorrow or the next

**Comment by Gilianp** [comment]
Oh, thank you! Awesome!
