### ISSUE TITLE
Error:Module 'com.github.brianPlummer:tinydancer:0.1.2' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by yanchunlan** [friendlyrobotnyc/TinyDancer#64]

**Comment by denabelarde** [comment]
+1
This occurs when adding this line `maven { url "https://jitpack.io" }`on the project level build.gradle

**Comment by digitalbuddha** [comment]
This seems to be a problem with jitpack and not us as we have 0 dependencies that use jitpack nor do we offer support for it.  I'd open an issue on their side instead
